import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/navbar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const theSeasons = localFont({
  src: [
    {
      path: "../../public/fonts/The Seasons Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/The Seasons Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/The Seasons Light Italic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../../public/fonts/The Seasons Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-the-seasons",
});

const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Helvetica-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${theSeasons.variable}
        ${helvetica.variable}
        h-full
        antialiased
      `}
    >
      <body className="min-h-[100dvh] flex flex-col">
        <Navbar />

        {children}
      </body>
    </html>
  );
}
